'use strict';

const { GITHUB_TOKEN, GITHUB_USERNAME, RED_PORTAL_OWNER, RED_PORTAL_REPO, RED_PORTAL_BRANCH } = require('./config');

const GH_API = 'https://api.github.com';

/** Shared headers for every GitHub request. */
function ghHeaders(extra = {}) {
  return {
    'Authorization': `Bearer ${GITHUB_TOKEN}`,
    'Accept':        'application/vnd.github+json',
    'X-GitHub-Api-Version': '2022-11-28',
    'Content-Type':  'application/json',
    'User-Agent':    'red-portal-bot/1.0',
    ...extra,
  };
}

/** Generic GitHub API call with error handling. */
async function ghFetch(method, path, body) {
  const opts = { method, headers: ghHeaders() };
  if (body) opts.body = JSON.stringify(body);
  const res = await fetch(`${GH_API}${path}`, opts);
  const data = await res.json().catch(() => ({}));
  if (!res.ok) {
    throw new Error(`GitHub ${method} ${path} → ${res.status}: ${JSON.stringify(data)}`);
  }
  return data;
}

/** Convert game name to a valid, short GitHub repo slug. */
function toSlug(name) {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .substring(0, 45);
}

/**
 * Create a new public GitHub repository.
 * Automatically appends a short timestamp suffix if the name is taken.
 * @returns {{ repoName: string, repoUrl: string, cloneUrl: string }}
 */
async function createRepo(gameName, description, suffix = '') {
  const base = toSlug(gameName) + suffix;
  const body = {
    name:        base,
    description: description || `Auto-generated by Red Portal Bot for "${gameName}"`,
    private:     false,
    auto_init:   true,   // ensures git object store is ready for the Data API
  };

  try {
    const data = await ghFetch('POST', '/user/repos', body);
    return {
      repoName: data.name,
      repoUrl:  data.html_url,
      cloneUrl: data.clone_url,
      owner:    data.owner.login,
    };
  } catch (err) {
    // 422 Unprocessable = name already taken → retry with timestamp
    if (err.message.includes('422') && !suffix) {
      const ts = Date.now().toString(36);
      return createRepo(gameName, description, `-${ts}`);
    }
    throw err;
  }
}

/**
 * Create the initial index.html in a repository.
 * The repo must exist (just created, empty).
 */
async function pushIndexHtml(owner, repoName, htmlContent, commitMsg) {
  const encoded = Buffer.from(htmlContent, 'utf-8').toString('base64');
  const data = await ghFetch('PUT', `/repos/${owner}/${repoName}/contents/index.html`, {
    message: commitMsg || 'Initial commit: add index.html',
    content: encoded,
  });
  return data;
}

/**
 * Push many files to a freshly-created, empty repository in a single commit.
 * Uses the Git Data API (blobs → tree → commit → ref) instead of the
 * contents API, since the contents API only supports one file per request
 * and would be far too slow for a crawled game with dozens of assets.
 *
 * @param {string} owner
 * @param {string} repoName
 * @param {Object<string, {bytes: Buffer, isText: boolean}>} files  localPath → file data
 * @param {string} commitMsg
 */
async function pushFiles(owner, repoName, files, commitMsg) {
  const paths = Object.keys(files);
  if (paths.length === 0) throw new Error('pushFiles called with no files');

  // 1) Get the current HEAD sha — auto_init creates an initial README commit
  //    which we need as the parent so our commit chains correctly.
  const headRef = await ghFetch('GET', `/repos/${owner}/${repoName}/git/ref/heads/main`);
  const parentSha = headRef.object.sha;

  // 2) Upload each file as a blob
  const blobs = {};
  for (const path of paths) {
    const { bytes, isText } = files[path];
    const body = isText
      ? { content: bytes.toString('utf-8'), encoding: 'utf-8' }
      : { content: bytes.toString('base64'), encoding: 'base64' };
    const blob = await ghFetch('POST', `/repos/${owner}/${repoName}/git/blobs`, body);
    blobs[path] = blob.sha;
  }

  // 2) Build a tree from the blobs (repo is empty, so no base tree needed)
  const treeItems = paths.map(path => ({
    path,
    mode: '100644',
    type: 'blob',
    sha:  blobs[path],
  }));
  const tree = await ghFetch('POST', `/repos/${owner}/${repoName}/git/trees`, { tree: treeItems });

  // 3) Create a commit with the auto_init commit as parent
  const commit = await ghFetch('POST', `/repos/${owner}/${repoName}/git/commits`, {
    message: commitMsg || `Initial commit: ${paths.length} file(s)`,
    tree:    tree.sha,
    parents: [parentSha],
  });

  // 4) Fast-forward the existing main branch ref (created by auto_init)
  await ghFetch('PATCH', `/repos/${owner}/${repoName}/git/refs/heads/main`, {
    sha:   commit.sha,
    force: false,
  });

  console.log(`[github] ✓ Pushed ${paths.length} file(s) to ${owner}/${repoName}`);
  return { commitSha: commit.sha, fileCount: paths.length };
}

/**
 * Fetch the current index.html from the Red Portal GitHub repo.
 * @returns {{ content: string, sha: string }}
 */
async function getRedPortalIndex() {
  const data = await ghFetch('GET', `/repos/${RED_PORTAL_OWNER}/${RED_PORTAL_REPO}/contents/index.html?ref=${RED_PORTAL_BRANCH}`);
  const content = Buffer.from(data.content, 'base64').toString('utf-8');
  return { content, sha: data.sha };
}

/**
 * Add a new game button to the #preLaunchGrid (Testing section)
 * in the Red Portal index.html and push it back to GitHub.
 * @param {string} gameName  Display name shown in the grid button.
 * @param {string} gameUrl   Full https:// URL for the href.
 */
async function addGameToTesting(gameName, gameUrl) {
  const { content, sha } = await getRedPortalIndex();

  // Verify this game isn't already in index.html (by URL)
  if (content.includes(gameUrl)) {
    throw new Error(`URL already present in index.html: ${gameUrl}`);
  }

  // Inject a new <a> button at the end of #preLaunchGrid
  const newButton =
    `        <a class="game-btn" href="${gameUrl}" target="_blank" rel="noopener noreferrer">` +
    `<span>${escapeHtml(gameName)}</span></a>`;

  // Match the preLaunchGrid div and its content, insert before closing </div>
  const gridRegex = /(<div class="games-grid" id="preLaunchGrid">)([\s\S]*?)(<\/div>)/;
  if (!gridRegex.test(content)) {
    throw new Error('Could not locate #preLaunchGrid in index.html');
  }

  const updated = content.replace(gridRegex, (_, open, inner, close) => {
    return open + inner + newButton + '\n      ' + close;
  });

  if (updated === content) {
    throw new Error('Regex replacement produced no change — aborting index.html update');
  }

  const encoded = Buffer.from(updated, 'utf-8').toString('base64');
  await ghFetch('PUT', `/repos/${RED_PORTAL_OWNER}/${RED_PORTAL_REPO}/contents/index.html`, {
    message: `bot: add "${gameName}" to Testing tab`,
    content: encoded,
    sha,
    branch:  RED_PORTAL_BRANCH,
  });

  console.log(`[github] ✓ Added "${gameName}" → Testing tab`);
}

/**
 * Fetch the Red Portal index.html and extract all existing game names + URLs
 * from both #gamesGrid and #preLaunchGrid.
 * @returns {{ names: string[], urls: string[] }}
 */
async function getExistingGames() {
  let content;
  try {
    ({ content } = await getRedPortalIndex());
  } catch (err) {
    console.warn('[github] Could not fetch index.html for existing-game check:', err.message);
    return { names: [], urls: [] };
  }

  const names = [];
  const urls  = [];

  // Match every game-btn href and span text
  const btnRegex = /<a class="game-btn" href="([^"]+)"[^>]*>\s*<span>([^<]+)<\/span>/g;
  let m;
  while ((m = btnRegex.exec(content)) !== null) {
    urls.push(m[1].trim());
    names.push(m[2].trim());
  }

  return { names, urls };
}

/** Run one GitHub repo search query and normalize the results. */
async function ghSearchRepos(query, perPage) {
  const q = encodeURIComponent(query);
  const data = await ghFetch('GET', `/search/repositories?q=${q}&sort=stars&per_page=${perPage}`);
  return (data.items || []).map(r => ({
    name:          r.full_name,
    url:           r.html_url,
    pagesUrl:      `https://${r.owner.login}.github.io/${r.name}/`,
    stars:         r.stargazers_count,
    description:   r.description || '',
    defaultBranch: r.default_branch,
    homepage:      r.homepage || '',
  }));
}

/**
 * Search GitHub repositories for an HTML5/browser version of a game.
 * Now the main fallback source (gn-math.dev was removed — its "search" was
 * a dead endpoint, see search.js), so this tries two passes instead of one:
 *   1. A narrow, high-precision query ("<name> html5 game").
 *   2. If that finds nothing, a broader "<name> game" query — catches repos
 *      that are a real browser port but don't happen to say "html5"
 *      anywhere in their name/description (e.g. tagged differently, or
 *      just named after the game itself).
 * Returns up to 8 candidates per pass; decision.js's own name-match +
 * reachability checks do the real filtering from there.
 */
async function searchGitHub(query) {
  const primary = await ghSearchRepos(`${query} html5 game`, 8);
  if (primary.length) return primary;

  console.log(`[github]   No results for "${query} html5 game" — retrying with a broader query…`);
  return ghSearchRepos(`${query} game`, 8);
}

function escapeHtml(str) {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

module.exports = {
  createRepo,
  pushIndexHtml,
  pushFiles,
  getRedPortalIndex,
  addGameToTesting,
  getExistingGames,
  searchGitHub,
  toSlug,
};
